<?php
return array(
	'field'		=> 	array(	'text'				=> 'Text',
							'email'				=> 'Email',
							'color'				=> 'Color',
							'tel'				=> 'Tel',
							'url'				=> 'Url',
							'range'				=> 'Range',
							'password'			=> 'Password',
							'hidden'			=> 'Hidden',
							'search'			=> 'Search',
							'1'					=> '---------',
							'file'				=> 'File',
							'files'				=> 'Files',
							'image'				=> 'Image',
							'images'			=> 'Images',
							'2'					=> '---------',
							'time'				=> 'Time',
							'date'				=> 'Date',
							'datetime'			=> 'Datetime',
							'week'				=> 'Week',
							'month'				=> 'Month',
							'date_picker'		=> 'Date Picker',
							'time_picker'		=> 'Time Picker',
							'date_time_picker'	=> 'Date Pime Pick'	,
							'3'					=> '---------',
							'radios'			=> 'Radios',
							'checkboxes'		=> 'Checkboxes',
							'switch'			=> 'Switch',
							'4'					=> '---------',
							'select'			=> 'Select',
							'model_select'		=> 'Model Select',
							'5'					=> '---------',
							'textarea'			=> 'Textarea',
							'html_editor'		=> 'Html Editor'),

	'select'		=> 	array("enum"	=>'select'),
	'exclude'		=> 	array("id","created_at","updated_at","deleted_at"),
	'include'		=> 	array("name"),
	'options'		=> 	array("checkbox","select","radio"),
	'versions'		=>  array('4.2' => 'Template Version 4.2', '5.0' => 'Template Version 5.0'),
	'package' => [
        'name'          => 'Product',
        'table'         => 'catalogue_products',
        'model'         => 'Lavalite\Catalogue\Models\Product',
        'permissions'   => ['admin' => ['view', 'create', 'edit', 'delete', 'image']],
        'image'         =>
            [
            'xs'        => ['width' =>'60',     'height' =>'45'],
            'sm'        => ['width' =>'100',    'height' =>'75'],
            'md'        => ['width' =>'460',    'height' =>'345'],
            'lg'        => ['width' =>'800',    'height' =>'600'],
            'xl'        => ['width' =>'1000',   'height' =>'750'],
            ],

	]
);